### ISSUE TITLE
Enter a valid email or mobile number error after running smoothly for a while.

### ISSUE THREAD

**Issue by cggaurav** [speric/kindle-highlights#11]
```
rake aborted!
KindleHighlights::Client::AuthenticationError: Unable to sign in, received error: 'Enter a valid email or mobile number'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:55:in `conditionally_sign_in_to_amazon'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:63:in `load_books_from_kindle_account'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/kindle-highlights-1.0.1/lib/kindle_highlights/client.rb:16:in `books'
/Users/cggaurav/Projects/apps/play/highlights/Rakefile:30:in `update'
/Users/cggaurav/Projects/apps/play/highlights/Rakefile:56:in `block in <top (required)>'
/Users/cggaurav/.rvm/gems/ruby-2.1.2/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => download
(See full trace by running task with --trace)
```

**Comment by cggaurav** [comment]
As I debug this, the first time I run kindle.books, I get the error, but not the same call again. Hmm.

**Comment by speric** [comment]
This is simply an error being returned from Amazon. Perhaps you are using the wrong sign in credentials?

**Comment by cggaurav** [comment]
Yeah, but this doesn't happen via the console or logging in via amazon.com and the credentials are right. Is this to do with request timing out if you have a lot of entries? I tried the `user-agent` option too. Hmm

**Comment by cggaurav** [comment]
@speric I fixed this by doing a double sign in. First time, I expect the error and second time I get the books. Custom for me - but if it happens to more people, open to submitting a PR for another retry.

![](http://d.cggaurav.net/d2TY+)

**Comment by speric** [comment]
Thanks @cggaurav!

**Comment by gmchande** [comment]
I get this same problem. Does Amazon hate people named 'Gaurav'? This is super odd.

**Comment by smitmartijn** [comment]
I'm having the same issue, but my name isn't Guarav. ;-) 

@cggaurav could you share the code which you used to fix it? Thanks!

**Comment by cggaurav** [comment]
@smitmartijn @gauravmc I am using my fork. https://github.com/cggaurav/highlights

**Comment by sirupsen** [comment]
https://github.com/speric/kindle-highlights/issues/12 should fix this

**Comment by whacked** [comment]
WFM :+1:

**Comment by sirupsen** [comment]
@speric just released in `1.0.2` that has this fix :)

**Comment by afomi** [comment]
I've upgraded to `1.0.2` and am still seeing the login error consistently (in multiple environments): `Unable to sign in, received error: 'Enter a valid email or mobile number'`

I'm looking through Amazon settings seeing if changing settings helps, but no luck so far. Any ideas?

**Comment by blackarcanis** [comment]
Same issue for me.
+1
